title: Tamas Szabo
description: Senior Data Analyst | Data Visualization Expert
baseurl: "/portfolio" 
url: "https://tamszabo.github.io/"

# Navigation links for the header
header_pages:
  - index.html
  - cv.md
  - blog.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/
future: true
