title: Tamas Szabo
description: Senior Data Analyst | Data Visualization Expert
baseurl: "" 
url: "https://tamasszabo.org/"
google_analytics: "G-4KH57STRSC"

# Navigation links for the header
header_pages:
  - index.html
  - cv.md
  - blog.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/
future: true
